quivers.settings:
  type: config_object
  label: 'Quivers settings'
  mapping:
    api_mode:
      type: string
      label: 'API mode'
    business_refid:
      type: string
      label: 'Business RefId'
    quivers_api_key:
      type: string
      label: 'Quivers API key'
    drupal_api_base_url:
      type: string
      label: 'Drupal API Base URL'
    consumer_key:
      type: string
      label: 'OAuth Consumer Key'
    consumer_secret:
      type: string
      label: 'OAuth Consumer Secret'
    middleware_profile_id:
      type: string
      label: 'Middleware Profile Id'
    quivers_marketplaces:
      type: sequence
      label: 'Quivers Marketplaces'
      mapping:
        quivers_marketplace_id:
          type: string
    quivers_claiming_groups:
      type: sequence
      label: 'Quivers Claiming Group Ids'
      mapping:
        quivers_claiming_group_id:
          type: string

quivers.tax_settings:
  type: config_object
  label: 'Quivers Tax Settings'
  mapping:
    marketplaces:
      type: sequence
      label: 'Marketplaces'
      sequence:
        type: quivers_marketplace_configuration

quivers_marketplace_configuration:
  type: mapping
  mapping:
    store_id:
      type: string
      label: 'Store Id'
    quivers_marketplace_id:
      type: string
      label: 'Quivers Marketplace Id'
    quivers_claiming_group_ids:
      type: string
      label: 'Quviers Claiming Groups Ids'
