quivers.settings:
  type: config_object
  label: 'Quivers Integration settings'
  mapping:
    api_mode:
      type: string
      label: 'Quivers Sandbox Enabled'
    aud:
      type: string
      label: 'AUD Marketplace ID'
    cad:
      type: string
      label: 'CAD Marketplace ID'
    eur:
      type: string
      label: 'EUR Marketplace ID'
    gbp:
      type: string
      label: 'GBP Marketplace ID'
    jpy:
      type: string
      label: 'JPY Marketplace ID'
    usd:
      type: string
      label: 'USD Marketplace ID'
    default_tax_code:
      type: string
      label: 'Default Tax Code'
    claiming_groups:
      type: string
      label: 'Claiming Groups'
    quivers_api_key:
      type: string
      label: 'Quivers API key'
    business_refid:
      type: string
      label: 'Business RefId'
    drupal_integration_base_url:
      type: string
      label: 'Drupal Integration Base URL'
    drupal_integration_username:
      type: string
      label: 'Drupal Integration Username'
    drupal_integration_auth_token:
      type: string
      label: 'Drupal Integration Auth Token'

