quivers.settings:
  type: config_object
  label: 'Quivers settings'
  mapping:
    api_mode:
      type: string
      label: 'API mode'
    aud_marketplace:
      type: string
      label: 'AUD Marketplace ID'
    cad_marketplace:
      type: string
      label: 'CAD Marketplace ID'
    eur_marketplace:
      type: string
      label: 'EUR Marketplace ID'
    gbp_marketplace:
      type: string
      label: 'GBP Marketplace ID'
    jpy_marketplace:
      type: string
      label: 'JPY Marketplace ID'
    usd_marketplace:
      type: string
      label: 'USD Marketplace ID'
