quivers.settings:
  type: config_object
  label: 'Quivers settings'
  mapping:
    api_mode:
      type: string
      label: 'API mode'
    business_refid:
      type: string
      label: 'Business RefId'
    quivers_api_key:
      type: string
      label: 'Quivers API key'
    drupal_api_base_url:
      type: string
      label: 'Drupal API Base URL'
    marketplaces:
      type: sequence
      label: 'Marketplaces'
      sequence:
        type: quivers_marketplace_configuration

quivers_marketplace_configuration:
  type: mapping
  mapping:
    store_id:
      type: string
      label: 'Store Id'
    quivers_marketplace_id:
      type: string
      label: 'Quivers Marketplace Id'
    quivers_claiming_group_ids:
      type: string
      label: 'Quviers Claiming Groups Ids'
